name: Update public Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version of SDK'
        required: true

jobs:
  update-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout first repository
        uses: actions/checkout@v4
        with:
          repository: 'Bliss00/Packages'
          ref: main
          path: Packages
          token: ${{ secrets.TOKEN }}

      - name: Read SDKPackage.swift content
        id: read-file
        run: |
          content=$(cat Packages/Packages/${{ inputs.version }}/SDKPackage.swift)
          echo "::set-output name=content::$content"

      - name: Checkout second repository
        uses: actions/checkout@v2
        with:
          repository: 'Bliss00/Testing'
          ref: main
          path: Testing
          token: ${{ secrets.TOKEN }}

      - name: Create new branch
        run: |
          cd Testing
          git checkout -b release-${{ inputs.version }}

      - name: Update Package.swift
        run: |
          echo "${{ steps.read-file.outputs.content }}" > Testing/Package.swift
          cd Testing
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Package.swift
          git commit -m "[UPDATE] SDK Package (${{ inputs.version }})"

      - name: Push changes
        run: |
          cd Testing
          git push origin release-${{ inputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: "COMMIT MESSAGE"
          branch: release-${{ inputs.version }}
          title: "TITLE"
          body: "BODY"
          base: main
