name: Update Binary Target URL and Create Pull Request

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'New URL to the Swift binary framework ZIP file'
        required: true
      version:
        description: 'Version number for release branch (e.g., v1.0.0)'
        required: true

jobs:
  update_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "actions@example.com"
          git config user.name "GitHub Actions"

      - name: Update URL in Package.swift
        run: |
          sed -i "s#url: .*#url: \"$INPUT_URL\"#" Package.swift
          git add Package.swift
          git commit -m "Update binary target URL"

      - name: Create Release Branch
        run: |
          git checkout -b release-${{ github.event.inputs.version }}

      - name: Push changes to release branch
        uses: ad-m/github-push-action@master
        with:
          branch: release-${{ github.event.inputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update binary target URL and create release branch"
          title: "Update binary target URL and create release branch for version ${{ github.event.inputs.version }}"
          body: |
            Changes made:
            - Updated binary target URL and checksum in Package.swift

            Release branch created for version ${{ github.event.inputs.version }}.

          branch: release-${{ github.event.inputs.version }}
          base: main
