name: Update BinaryTarget URLs in Package.swift

on:
  workflow_dispatch:
    inputs:
      coreSDKURL:
        description: 'New URL for TestingCoreSDK'
        required: true
      uiSDKURL:
        description: 'New URL for TestingUISDK'
        required: true
      branchName:
        description: 'Branch name for the changes'
        required: true

jobs:
  update-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Package.swift URLs
      run: |
        CORE_SDK_URL="${{ github.event.inputs.coreSDKURL }}"
        UI_SDK_URL="${{ github.event.inputs.uiSDKURL }}"

        sed -i "/.binaryTarget(name: \"TestingCoreSDK\",/{n;s|url: \".*\",|url: \"$CORE_SDK_URL\",|}" Package.swift
        sed -i "/.binaryTarget(name: \"TestingUISDK\",/{n;s|url: \".*\",|url: \"$UI_SDK_URL\",|}" Package.swift

    - name: Create and push new branch
      run: |
        BRANCH_NAME=${{ github.event.inputs.branchName }}
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b $BRANCH_NAME
        git add Package.swift
        git commit -m "Update binary target URLs"
        git push origin $BRANCH_NAME
