name: Update BinaryTarget URLs and Create Release Branch

on:
  workflow_dispatch:
    inputs:
      coreSDKURL:
        description: 'New URL for TestingCoreSDK'
        required: true
        default: ''
      uiSDKURL:
        description: 'New URL for TestingUISDK'
        required: true
        default: ''
      version:
        description: 'Release version'
        required: true
        default: ''

jobs:
  update-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Package.swift URLs
      run: |
        CORE_SDK_URL=${{ github.event.inputs.coreSDKURL }}
        UI_SDK_URL=${{ github.event.inputs.uiSDKURL }}
        sed -i "0,/url: \".*\",/{s|url: \".*\",|url: \"$CORE_SDK_URL\",|}" Package.swift
        sed -i "1,/url: \".*\",/{s|url: \".*\",|url: \"$UI_SDK_URL\",|}" Package.swift

    - name: Create and push release branch
      run: |
        VERSION=${{ github.event.inputs.version }}
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b release-$VERSION
        git add Package.swift
        git commit -m "Update binary target URLs for release $VERSION"
        git push origin release-$VERSION

    - name: Create pull request
      id: create_pr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
        head: release-${{ github.event.inputs.version }}
        title: 'Release ${{ github.event.inputs.version }}'
        body: 'This pull request updates the binary target URLs for the release ${{ github.event.inputs.version }}.'
        draft: false
