name: Update Binary Target URL and Create Pull Request

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'New URL to the Swift binary framework ZIP file'
        required: true
      version:
        description: 'Version number for release branch (e.g., v1.0.0)'
        required: true

jobs:
  update_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.5'  # Replace with your Swift version if necessary

      - name: Download and compute checksum for binary framework
        run: |
          mkdir framework
          cd framework
          curl -LO ${{ github.event.inputs.url }}
          framework_zip=$(basename ${{ github.event.inputs.url }})
          unzip $framework_zip
          # Calculate SHA256 checksum
          checksum=$(shasum -a 256 $framework_zip | cut -d ' ' -f 1)
          cd ..

      - name: Update URL and checksum in Package.swift
        run: |
          sed -i "s|old-url-here|${{ github.event.inputs.url }}|g" Package.swift
          sed -i "s|old-checksum-here|${checksum}|g" Package.swift
          git add Package.swift
          git commit -m "Update binary target URL and checksum"

      - name: Create Release Branch
        run: |
          git checkout -b release-${{ github.event.inputs.version }}

      - name: Push changes to release branch
        uses: ad-m/github-push-action@master
        with:
          branch: release-${{ github.event.inputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update binary target URL and create release branch"
          title: "Update binary target URL and create release branch for version ${{ github.event.inputs.version }}"
          body: |
            Changes made:
            - Updated binary target URL and checksum in Package.swift

            Release branch created for version ${{ github.event.inputs.version }}.

          branch: release-${{ github.event.inputs.version }}
          base: main
